import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ApolloWrapper from "@/components/ui/ApolloWrapper";
import { MyProvider } from "@/context/ContextProvider";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";

// Importing custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.snow.css"
          rel="stylesheet"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.js"
          defer
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <MyProvider>
            <Navbar />
            {children}
            <Footer/>
          </MyProvider>
        </ApolloWrapper>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
